---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bluecompute-web-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bluecompute
        tier: frontend
        micro: web-bff
    spec:
      containers:
      - name: web-ce
        image: registry.ng.bluemix.net/hc_dev/bluecompute-web:version
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bluecompute-web
  labels:
    app: bluecompute
    tier: frontend
    micro: web-bff
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30005
  selector:
    app: bluecompute
    tier: frontend
    micro: web-bff
...
